import { notFound } from "next/navigation";
import { DataUnavailableState } from "@/components/common/DataUnavailableState";
import { PageFrame } from "@/components/common/PageFrame";
import { EntityArticle } from "@/components/content/EntityArticle";
import { englishContent } from "@/lib/content";
import { isScholarContent } from "@/data/templates/scholar-template";
import { getScholarBySlug } from "@/lib/entities/scholars";
import { generateScholarMeta } from "@/lib/seo";
import { publishedSlugs } from "@/lib/static-params";
import { JsonLdPerson } from "@/components/seo/JsonLdPerson";
import { getInternalLinks } from "@/lib/internal-links";
import { sourceItemsForEntity } from "@/lib/knowledge-entity-presentation";
import { DATA_UNAVAILABLE, loadDataPage } from "@/lib/data-page";
export const revalidate = 3600;
export const dynamicParams = false;
export async function generateStaticParams() { return publishedSlugs("scholar"); }
export async function generateMetadata({ params }: PageProps<"/scholars/[slug]">) { const slug = (await params).slug; const item = await loadDataPage(() => getScholarBySlug(slug)); return item && item !== DATA_UNAVAILABLE ? generateScholarMeta(item) : {}; }
export default async function ScholarPage({ params }: PageProps<"/scholars/[slug]">) { const state = await loadDataPage(async () => { const item = await getScholarBySlug((await params).slug); return item ? { item, internalLinks: await getInternalLinks("scholar", item.slug) } : null; }); if (state === DATA_UNAVAILABLE) return <PageFrame><DataUnavailableState /></PageFrame>; if (!state) notFound(); const { item, internalLinks } = state; const content = englishContent(item.contentJsonb); if (!isScholarContent(content)) notFound(); const theoryBySlug = new Map(item.theories.map(({ theory }) => [theory.slug, theory])); return <><JsonLdPerson name={item.name} description={item.bioEn || content.overview} path={`/scholars/${item.slug}`} /><PageFrame><EntityArticle kind="Scholar" title={item.name} summary={item.bioEn} overview={content.overview} breadcrumb={[{ label: "Scholars", href: "/scholars" }]} links={internalLinks.map(({ label, href, reason }) => ({ label, href, description: reason }))} sources={sourceItemsForEntity(content)}><section className="prose-section"><h2>Academic positioning</h2><p>{content.academic_identity.discipline} · {content.academic_identity.role}</p></section><section className="prose-section"><h2>Relationship to Syntag theories</h2><ul>{content.theory_relationships.map((entry) => { const theory = theoryBySlug.get(entry.theory_slug); return <li key={entry.theory_slug}>{theory ? <a href={`/theories/${theory.slug}`}>{theory.titleEn}</a> : entry.theory_slug.replaceAll("-", " ")} — {entry.relationship}: {entry.description}</li>; })}</ul></section><section className="prose-section"><h2>Representative works and contributions</h2><ul>{content.representative_works.map((entry) => <li key={entry.title}>{entry.work_slug ? <a href={`/works/${entry.work_slug}`}>{entry.title}</a> : entry.title} — {entry.contribution}</li>)}</ul></section><section className="prose-section"><h2>Influence, development, critique, or collaboration</h2><ul>{content.scholarly_relations.map((entry) => <li key={`${entry.kind}-${entry.description}`}>{entry.kind}: {entry.description}</li>)}</ul></section><section className="prose-section"><h2>Attribution boundary</h2><ul>{content.attribution_boundaries.map((entry) => <li key={entry}>{entry}</li>)}</ul></section><section className="prose-section"><h2>Reading path</h2><ol>{content.reading_path.map((entry) => <li key={entry.order}><strong>{entry.title}</strong> — {entry.purpose}</li>)}</ol></section></EntityArticle></PageFrame></>; }
